[package]
name = "peeps-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "peeps"
path = "src/main.rs"

[dependencies]
facet.workspace = true
facet-json.workspace = true
facet-value.workspace = true
figue.workspace = true
ureq.workspace = true
