[package]
name = "peeps-wire"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
facet.workspace = true
facet-json.workspace = true
peeps-types.workspace = true
