[package]
name = "moire-trace-capture"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
backtrace.workspace = true
libc.workspace = true
moire-trace-types.workspace = true
