[package]
name = "peeps-examples"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
dialoguer = { version = "0.12", features = ["fuzzy-select"] }
libc.workspace = true
ureq.workspace = true
ctrlc = "3.4"
