[package]
name = "peeps-futures"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
facet.workspace = true
peeps-types.workspace = true
tokio.workspace = true

[features]
diagnostics = []
