[package]
name = "peeps-tasks"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
backtrace.workspace = true
facet.workspace = true
peeps-types.workspace = true
tokio.workspace = true

[features]
diagnostics = []
