[package]
name = "peeps-roam"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
facet.workspace = true

# TODO: Add roam-session dependency when ready to integrate
